settings:
  title: 'Deepcord Status'
  url: 'https://status.deepcord.ml' # used for Slack messages
  logo: ff32cdd5af4fc7b1742b4d0c0d57e0a7.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Active Incident'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: deepcord.ml # unique identifier
    name: Website
    description: 'The main Deepcord website' # default=empty
    url: 'https://deepcord.ml' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: status.deepcord.ml
    name: Deepcord Status
    description: 'The Deepcord Status (basically this xd)'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: dev.fosscord.com
    name: Fosscord
    description: 'Fosscord dev instance'
    url: 'dev.fosscord.com'
    method: GET
    expectStatus: 200
